Fixed "IllegalStateException: Jenkins URL null" in PodTemplateStepExecution
When KubernetesCloud.directConnection is used and no Jenkins URL
is configured (e.g. because Jenkinsfile Runner does not expose an
http port -> no Jenkins URL) the following Exception is thrown:

java.lang.IllegalStateException: Jenkins URL for Kubernetes is null
	at org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud.getJenkinsUrlOrDie(KubernetesCloud.java:330)
	at org.csanchez.jenkins.plugins.kubernetes.pipeline.PodTemplateStepExecution.start(PodTemplateStepExecution.java:119)