Remove default connectorHost
Need to pass it explicitly because if ip does not exist tests will fail with

    java.net.BindException: Cannot assign requested address