[JENKINS-59000] Upgrade kubernetes-client to 4.4.2
To get the fix in https://github.com/fabric8io/kubernetes-client/pull/1669

Origin header is set with port -1 when no port is present in the Kubernetes API url

Causing an error on exec

```
java.net.ProtocolException: Expected HTTP 101 response but was '403 Forbidden'
```