delete slave pod when slave pod got provisioned by failed to run
Added call to deleteSlavePod when computer is null.
When Jenkins master encounter disk full issue, Jenkins master failed to write out the queue file /var/jenkins_home/queue.xml
and also had some other file write issue, like: 
Failed to create agent log directory /var/jenkins_home/logs/slaves/{slavePodName}
and also:
Provisioned agent {slavePodName} failed to launch
java.nio.file.FileSystemException: /var/jenkins_home/nodes/{slavePodName}: No space left on device
Also, the kubernetes plugin will try to provision a new pod every second and it will exhaust cloud resource in very quickly.
And since no "delete" command send to cloud, the nominated cloud is not able to delete these pods.