If namespace is not provided nor autoconfigured should use default
Otherwise it will fail with
io.fabric8.kubernetes.client.KubernetesClientException: Namespace not specified. But operation requires namespace.

Test pod creation on global config page